T: 1
alpha: 0.1
batch_size: 100
beta: 0.75
bias: false
bn: true
clf_path: /home/math/dragos.manta/contrastive/ContrastiveTeamO/regularization/runs/runs_lambda_10/classifier_best.pth.tar
criterion: logistic
data_dir: /home/math/oberman-lab/data
dropout: 0
dt: 0.1
gamma: 0.05
init_type: gaussian
last_layer_nonlinear: false
max_inner: 30
max_outer: 30
model_args: '{}'
model_path: /home/math/dragos.manta/contrastive/ContrastiveTeamO/regularization/runs/runs_lambda_10/encoder_best.pth.tar
norm: L2
num_images: 1000
parallel: false
random_subset: true
save_images: false
seed: 0
strict: false
