AT_ball: 0.5
AT_steps: 10
add_gaussian: false
adv_train: false
batch_size: 128
bias: false
bn: true
classes: 10
cutout: 0
datadir: /home/campus/oberman-lab/data/cifar10
dataset: cifar10
decay: 0.0005
dropout: 0
epochs: 200
fd_order: O1
filename: data.pkl
greyscale: false
kernel_size: 3
last_layer_nonlinear: false
log_interval: 100
logdir: ./logs/cifar10/ResNet18/20-07-07T125950
loss_function: null
loss_weight: null
lr: 0.1
lr_schedule: '[[0,1],[60,0.2],[120,0.04],[160,0.008]]'
model: ResNet18
model_args: '{}'
model_dir: null
momentum: 0.9
norm: L2
num_images: 1000
num_samples: 10
parallel: false
pen_const: null
pth_name: best.pth.tar
random_labels: false
random_subset: false
retrain: false
save_images: false
save_path: null
seed: 0
std: 0.1
strict: false
test_batch_size: 100
tik: null
train_pen: false
valid_size: null
