alpha: 0.1
batch_size: 100
bias: false
bn: true
clf_path: /home/campus/ryan.campbell2/ContrastiveTeamO/cifar10/runs/classifier_best.pth.tar
criterion: top1
data_dir: /home/campus/oberman-lab/data/
dropout: 0
eps: 4.0
iters: 100
last_layer_nonlinear: false
loss_function: kl_div
model_args: '{}'
model_path: /home/campus/ryan.campbell2/ContrastiveTeamO/cifar10/runs/encoder_best.pth.tar
norm: L2
num_images: 1000
random_subset: false
seed: 0
