alpha: 0.1
batch_size: 100
bias: false
bn: true
clf_path: /home/math/dragos.manta/contrastive/ContrastiveTeamO/regularization/runs/runs_lambda_10/classifier_best.pth.tar
criterion: top1
data_dir: /home/math/oberman-lab/data/
dropout: 0
eps: 0.5
iters: 20
last_layer_nonlinear: false
loss_function: KL
model_args: '{}'
model_path: /home/math/dragos.manta/contrastive/ContrastiveTeamO/regularization/runs/runs_lambda_10/encoder_best.pth.tar
norm: L2
num_images: 1000
random_subset: true
seed: 0
