batch_size: 128
bias: false
bn: true
data_dir: /home/math/oberman-lab/data/
decay: 0.0
dropout: 0
encoder: ./runs/runs_lambda_10
epochs: 100
kernel_size: 3
last_layer_nonlinear: false
logdir: ./runs/runs_lambda_10
lr: 0.8
model: ResNet50
model_args: '{}'
num_test_images: 10000
num_train_images: 50000
random_subset: false
seed: 0
test_batch_size: 100
