batch_size: 128
bias: false
bn: true
cutout: 0
datadir: /home/math/oberman-lab/data/cifar10
dataset: cifar10
decay: 0.0005
dropout: 0
epochs: 200
fd_order: O1
greyscale: false
h: 0.01
kernel_size: 3
last_layer_nonlinear: false
log_interval: 100
logdir: ./runs_baseline_tik/runs
lr: 0.1
lr_schedule: '[[0,1],[60,0.2],[120,0.04],[160,0.008]]'
model: ResNet50
model_args: '{}'
momentum: 0.9
norm: L2
num_test_images: 10000
num_train_images: 50000
penalty: 0.1
random_subset: false
seed: 1598369336
test_batch_size: 100
