batch_size: 128
bias: false
bn: true
data_dir: /home/math/oberman-lab/data/
decay: 1.0e-05
dropout: 0
epochs: 100
fd_order: O1
h: 0.01
kernel_size: 3
last_layer_nonlinear: false
log_interval: 50
logdir: ./runs/runs_lambda_1
lr: 0.0003
lr_schedule: '[[0,1],[30,0.2],[60,0.04],[80,0.008]]'
model: ResNet50
model_args: '{}'
momentum: 0.9
norm: L2
penalty: 1.0
seed: 0
