batch_size: 128
bias: false
bn: true
cutout: 0
datadir: /home/math/oberman-lab/data/cifar10
dataset: cifar10
decay: 0.0005
dropout: 0
epochs: 200
greyscale: false
kernel_size: 3
last_layer_nonlinear: false
log_interval: 100
logdir: ./logs/cifar10/ResNet50/Aug-19-2020_13-48-11
lr: 0.1
lr_schedule: '[[0,1],[60,0.2],[120,0.04],[160,0.008]]'
model: ResNet50
model_args: '{}'
momentum: 0.9
seed: 1597859294
test_batch_size: 100
