alpha: 0.1
batch_size: 100
bias: false
bn: true
criterion: top1
data_dir: /home/math/oberman-lab/data/cifar10
dropout: 0
eps: 0.5
iters: 20
last_layer_nonlinear: false
loss_function: KL
model_args: '{}'
model_path: /home/math/dragos.manta/contrastive/ContrastiveTeamO/cifar10/runs_baseline_tik/runs_lambda_01/best.pth.tar
norm: L2
num_images: 10000
random_subset: false
seed: 0
