batch_size: 128
bias: false
bn: true
data_dir: /home/math/oberman-lab/data/
decay: 0.0
dropout: 0
epochs: 100
kernel_size: 3
last_layer_nonlinear: false
logdir: ./runs_fine_tuned/runs_5000
lr: 0.8
lr_schedule: '[[0,1],[60,0.2],[120,0.04],[160,0.008]]'
model: ResNet50
model_args: '{}'
momentum: 0.9
num_test_images: 10000
num_train_images: 5000
random_subset: true
seed: 0
test_batch_size: 100
weights: ./runs/encoder_best.pth.tar
